
name: .SRCINFO

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Creating the .SRCINFO file
        id: makepkg
        uses: smallstep/pkgbuild-action@v1.0.1
        run: makepkg --printsrcinfo > .SRCINFO
